### ISSUE TITLE
Update for DoW 2.0

### ISSUE THREAD

**Issue by panteror** [FeuerSturm/dowserverstatus#2]
Hi Feuersturm,

Do you plan to update the statusbar for dow 2.0 ? I did new images for the maps of dow 2.0. It's working for the beta 2.0 server.
Contact me on discord if needed.

Thanks

**Comment by FeuerSturm** [comment]
Hey,
currently I'm pretty busy with real life stuff, but I'll for sure update the code once
neccessary.
I've merged your pull request, thanks for you work! :-)
